# Generated by Django 5.2.7 on 2025-11-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_scrapping", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="web",
            name="name",
        ),
        migrations.AddField(
            model_name="web",
            name="article_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="web",
            name="date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="web",
            name="original_content",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="web",
            name="text_content",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="web",
            name="url",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
