# Generated by Django 5.2.7 on 2025-11-02 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_scrapping", "0002_remove_web_name_web_article_name_web_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="web",
            name="article_name",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="web",
            name="original_content",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="web",
            name="text_content",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="web",
            name="url",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
