# Generated by Django 5.2.7 on 2025-11-02 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "web_scrapping",
            "0003_alter_web_article_name_alter_web_original_content_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="web",
            name="article_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="web",
            name="original_content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="web",
            name="text_content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="web",
            name="url",
            field=models.TextField(blank=True, null=True),
        ),
    ]
